apiVersion: v1
kind: Service
metadata:
  name: {{ include "bdc-chatbot.fullname" . }}
  labels:
    {{- include "bdc-chatbot.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 8501
      targetPort: streamlit
      protocol: TCP
      name: streamlit
    - port: 8000
      targetPort: api
      protocol: TCP
      name: api
  selector:
    {{- include "bdc-chatbot.selectorLabels" . | nindent 4 }}
